### ISSUE TITLE
Not launching Sublimetext

### ISSUE THREAD

**Issue by niladam** [spatie/laravel-ray#6] opened 2021-01-07 16:15 UTC
Hey @freekmurze thank you for this tool. It was an instant buy.

I'm on Mac (latest) and using the latest version of the app.

I selected my editor as Sublime but nothing seems to happen when i click a line number.

Is this the intended functionality ?

Or do i have to install something else to get this working ?

**Comment by freekmurze** [comment] 2021-01-07 16:17
This should work out of the box. Our you using the latest version of Sublime?

We'll get this fixed shortly!

**Comment by niladam** [comment] 2021-01-07 16:20
@freekmurze Yes. I'm on the latest (released!) version of Sublime.

<img width="341" alt="Screenshot 2021-01-07 at 18 18 55" src="https://user-images.githubusercontent.com/4151765/103916221-d6362300-5114-11eb-9b86-2beb6484cd7a.png">

**Comment by freekmurze** [comment] 2021-01-08 14:25
This seems to be a duplicate of https://github.com/spatie/ray/issues/57

We'll track it in that issue.

**Closed by freekmurze** 2021-01-08 14:25 UTC
