### ISSUE TITLE
Laravel signed URLs are getting corrupted in Mail view

### ISSUE THREAD

**Issue by htulibacki** [spatie/laravel-ray#343] opened 2024-04-18 14:34 UTC
**Describe the bug**
When you click on a button, like the one for email verification, you always get a 403 error - invalid signature. Seems like the "=" sign is getting dropped.

**Versions**
Ray version (you can see this in "About Ray"):  2.7.5

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.41.1
- spatie/laravel-ray package version (if applicable): 1.36.1

PHP version: 8.3
Laravel version: 11.4

**To Reproduce**
1. Send default Fortify email verification message.
2. Click on Confirm button (or even on link in the footer).
3. 403 - Invalid signature

**Expected behavior**
There should't be any error.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 14.4.1 (23E224)

**Comment by freekmurze** [comment] 2024-04-22 13:51
I've tried to reproduce this using our demo app.

It contains a mailable with a link containing `=`

https://github.com/spatie/laravel-ray-demo-app/blob/6bb9f8d9e1c8758d3fbedfe354ab129d5a585003/resources/views/mails/test.blade.php#L6

You can send that mail to Ray using `php artisan mail`

When clicking the "View order" button in the mail, the correct link (`https://spatie.be/?hey=yo&option=value`) opens in the browser.

So, it seems to be working. Could you PR a link that does not work to our demo app?

**Comment by htulibacki** [comment] 2024-04-22 17:07
Sure!

https://github.com/spatie/laravel-ray-demo-app/pull/3

**Comment by edalzell** [comment] 2024-05-14 16:35
I get this too, only w/ signed urls

**Comment by freekmurze** [comment] 2024-05-24 08:06
This is fixed in the latest version.

**Closed by freekmurze** 2024-05-24 08:06 UTC
