### ISSUE TITLE
Application tests fail because of Ray's event listener (even when disabled)

### ISSUE THREAD

**Issue by sebastiaanluca** [spatie/laravel-ray#109] opened 2021-01-18 19:06 UTC
**Describe the bug**

Even with Ray completely disabled via the config env variable, our application tests fail because Ray listens to the events and receives an object instead of a string (for the event name, I think). This happens when custom Eloquent events are used.

For example, in a model:

```php
    protected $dispatchesEvents = [
        'created' => MyCustomEvent::class,
    ];
```

```
testing.ERROR: Argument 1 passed to Spatie\LaravelRay\RayServiceProvider::Spatie\LaravelRay\{closure}() must be of the type string, object given, called in projectdir/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 388 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Spatie\\LaravelRay\\RayServiceProvider::Spatie\\LaravelRay\\{closure}() must be of the type string, object given, called in projectdir/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 388 at projectdir/vendor/spatie/laravel-ray/src/RayServiceProvider.php:171)

#0 projectdir/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(388): Spatie\\LaravelRay\\RayServiceProvider->Spatie\\LaravelRay\\{closure}(Object(MyClic\\Events\\MyCustomEvent), Array)
```

**So basically it passed the custom event class instead of the string name of the event.**

Line 171 in RayServiceProvider:

```php
        Event::listen('*', function (string $event, array $arguments) {
            /** @var \Spatie\LaravelRay\EventLogger $eventLogger */
            $eventLogger = app(EventLogger::class);

            $eventLogger->handleEvent($event, $arguments);
        });
```

**Versions**
Ray version (you can see this in "About Ray"):

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.7.2
- spatie/laravel-ray package version (if applicable): 1.5.2

PHP version: 7.4.14
Laravel version (if applicable): 8.22.1

**To Reproduce**
1. Run any application test that triggers an event

**Expected behavior**
The tests pass or at least run 😄

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version N/A

**Comment by freekmurze** [comment] 2021-01-22 21:31
Closing this one for now, as I cannot reproduce this. Feel free to post a link to an app that allows me to reproduce the issue and I'll reopen the issue.

**Closed by freekmurze** 2021-01-22 21:31 UTC

**Comment by sebastiaanluca** [comment] 2021-01-22 21:32
I'll let you know in the upcoming week(s) when I've dedicated some time to debugging this properly 👍

**Comment by sebastiaanluca** [comment] 2021-01-25 18:07
Debugged this properly and found the cause: the type-hinting on the closure in the Ray service provider that listens to all events (`*` wildcard) conflicted with a specific test setup we had. Our test setup worked without Ray (and with Ray when removing the type hints), but Ray expected a `string $event` while our setup registered a listener that sent it an instance of a class (instead of a string event or event class name).

I refactored the setup a bit so it does things without wrapping a closure in another closure. The goal here is to prepend the existing listeners of an event with a closure listener to properly set it up when running our tests (without touching our project code). Laravel doesn't provide an out-of-the-box way to do this.

```php
<?php

$listeners = app(Dispatcher::class)->getListeners(YourEvent::class);

// The dispatcher returns the already parsed closures which are not usable
// on their own, so we need to unwrap them first.
$listeners = collect($listeners)->map(static function (Closure $listener) {
    $use = (new ReflectionFunction($listener))->getStaticVariables();
    $listener = $use['listener'] ?? $listener;
    $wildcard = $use['wildcard'] ?? false;

    return compact('listener', 'wildcard');
});

$createUserInfoListener = [
    'wildcard' => false,
    'listener' => static function (YourEvent $event): void {
        // Do some extra stuff in a listener specific for testing
    },
];

$listeners = array_prepend($listeners->all(), $createUserInfoListener);

app(Dispatcher::class)->forget(YourEvent::class);

foreach ($listeners as ['listener' => $listener, 'wildcard' => $wildcard]) {
    app(Dispatcher::class)->listen($wildcard ? '*' : YourEvent::class, $listener);
}
```
