### ISSUE TITLE
Queries with values that contain question marks are incorrectly logged

### ISSUE THREAD

**Issue by squatto** [spatie/laravel-ray#78] opened 2021-01-12 23:09 UTC
**Describe the bug**
When using `showQueries()`, if a query has a _value_ that contains a question mark `?`, the query is incorrectly logged because the question mark is replaced with the next bound value. This query is a great example: (I trimmed the actual values, so the JSON isn't valid...)

```sql
update
  `sba_api_request_logs`
set
  `was_successful` = "true",
  `response_code` = "200",
  `response_reason_phrase` = "OK",
  `response_headers` = "{"Content-Type":["application\/json"],...}",
  `response_data` = "{"count":1057,"next":"https:\/\/sandbox.forgiveness.sba.gov\/api\/naics\/"false"page=2","previous":null,"results":[...]}",
  `was_server_error` = "false",
  `was_client_error` = "2021-01-12 22:22:31",
  `sba_api_request_logs`.`updated_at` = "46"
where
  `id` = ?
```

The bound values are correct until the `response_data` value. There is a URL in that value that includes the string `?page=2`. The `?` is being replaced by the next bound value in the query - `"false"` - which should be bound to `was_server_error`. This causes each subsequent bound value to be shifted up, and the last bound value - `id` - remains `?`. There aren't any more bound values at that point, but it should be `"46"`, which was shifted up and bound instead to `updated_at`.

Let me know if that made any sense 😂  The first image below hopefully makes it more clear what I'm trying to say.

**Versions**
Ray version (you can see this in "About Ray"): 1.2.3

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.5.0
- spatie/laravel-ray package version (if applicable): 1.3.4

PHP version: 7.4.14
Laravel version: 8.21.0

**To Reproduce**
1. Enable `showQueries()`
2. Execute a query with a _value_ that contains a question mark `?`

**Expected behavior**
Question marks `?` within field values should not be replaced with bound values

**Screenshots**
This shows the bound values and the field they should be bound to:
![image](https://user-images.githubusercontent.com/748444/104385340-4fa48b80-54f0-11eb-8e30-f0fd1d7d24f4.png)

This is a different query that shows what is happening:
![image](https://user-images.githubusercontent.com/748444/104384884-7ca46e80-54ef-11eb-8a4a-3e0d1a92b28e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Big Sur 11.1 (20C69)

**Additional context**
N/A

**Comment by freekmurze** [comment] 2021-01-13 08:13
Thanks for reporting this!I

I could reproduce the issue, but it's kinda hard to fix. `$query->bindings`.

Given this piece of code:

```
$user->update(['name' => ' ? name ?' . now()->timestamp]);
```

This is what is displayed in Ray:

<img width="722" alt="image" src="https://user-images.githubusercontent.com/483853/104424376-955c6500-557f-11eb-8b0c-0f2b1ac51a14.png">

And this is the contents of the `ExecutedPayload`:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/483853/104424396-9c837300-557f-11eb-8396-da4bb9219c13.png">

Since the bindings is just an indexed array, I don't see a way of replacing the `?` in a correct way. 

I'm open for suggestions on how to go about this.

**Comment by squatto** [comment] 2021-01-13 08:59
Here is a way to replace the bindings in a correct way:

1. Create a completely random placeholder string made up of absolute nonsense. A string that will never possibly be found in a field name or a value.
2. Replace each `?` in the query with the placeholder
3. Loop through the bindings, replacing the first occurrence of the placeholder with each binding

Here's an example using your query and bindings:

```php
$sql = "update `users` set `name` = ?, `users`.`updated_at` = ? where `id` = ?";

$bindings = [
	" ? name ?1610525389",
  	"2021-01-13 08:09:49",
    1,
];

// replace each "?" in the query with a placeholder string
// that will NEVER be in an actual query OR value
// make sure that the placeholder is _complete_ nonsense!
$placeholder = ')/{!' . Str::random(20) . '/}!|';
$sql = str_replace('?', $placeholder, $sql);

// loop through the bindings and replace the first occurrence of the placeholder each time
foreach ($bindings as $binding) {
  $sql = Str::replaceFirst($placeholder, '"' . $binding . '"', $sql);
}
```

It's *extremely* important that the placeholder is a crazy string, otherwise you run the risk of a bound value being inserted into a previous bound value again. Take note of `$placeholder` in the example:

```php
$placeholder = ')/{!' . Str::random(20) . '/}!|';
```

I think it's a safe bet it's not going to be in a field name or value any time soon ;)

I used `'"' . $binding . '"'` to enclose the value in quotes so that it looks the same as Ray shows it.

Here's the final value of `$sql`:

```
update `users` set `name` = " ? name ?1610525389", `users`.`updated_at` = "2021-01-13 08:09:49" where `id` = "1"
```

**Comment by freekmurze** [comment] 2021-01-13 09:12
Thanks for your suggestion. Meanwhile, we found a way to handle this correctly inside the Ray app. This will be fixed in the next release 👍

**Closed by freekmurze** 2021-01-13 09:12 UTC

**Comment by AdrianMrn** [comment] 2021-01-13 11:14
This will be included in 1.2.5

**Comment by squatto** [comment] 2021-01-13 15:40
Wonderful, thank you very much for jumping on this!

**Comment by cby016** [comment] 2022-05-04 19:37
Found this thread from a google search. Here is a different way to log a query with question marks replaced with the binding values.
		
```
// Quote query bindings if needed
$bindings = array_map(function ($value) {
	return is_string($value) ? DB::getPdo()->quote($value) : $value;
}, $query->bindings);

// Create regex array
$regexes = array_fill(0, count($bindings), '/\?/');

// Replace question marks with quoted bindings
$queryWithBindings = preg_replace($regexes, $bindings, $query->sql, 1);

// Log query
File::append (
	storage_path('/logs/query.log'),
	'[' . date('Y-m-d H:i:s') . ']' . PHP_EOL . $queryWithBindings . PHP_EOL . PHP_EOL
);
```
